### PR TITLE
add Rmd file to generate table for workshops

### PR DESCRIPTION
**Pull request by LiNk-NY**

### CODE REVIEW

**Comment by mdozmorov** [comment]
Tested locally, the code works and cleanly catches the missing DESCRIPTION files. Thanks, @LiNk-NY, wish I could help, was swamped with teaching

**Comment by mdozmorov** [comment]
Hi @LiNk-NY, the workshop page is being rendered incorrectly, https://bioc2020.bioconductor.org/workshops. I'm not immediately sure how to correct that - can you help?

**Comment by LiNk-NY** [comment]
Hi Mikhail, @mdozmorov 
I see it. 
Is there a way to do a test run of the website? 
I'll look into it.

**Comment by mtmorgan** [comment]
the README includes instructions on locally building the website.

**Comment by LiNk-NY** [comment]
Thanks Martin @mtmorgan 
It looks like the page renders much better using the `.html` product. I've added a PR at #83 
Let me know if this works. I am not sure why the table in the `.md` file is not rendering
properly...

**Pull request merged**
