### PR TITLE
add Rafa, Caroline, Kylie

### PR DESCRIPTION
**Pull request by HelenaLC**

### CODE REVIEW

**Comment by lwaldron** [comment]
I think conference speaker bios should focus on a) accomplishments, and b) interests related to the conference (e.g. work close to the "potential topic" column of the "Speakers_Bioc_Conference" spreadsheet). For Kylie, I would mention John M. Chambers Statistical Software Award over non bioinformatics-related work, which seems better suited to a personal website bio than a conference announcement, unless she suggested that bio for the website. If you think I'm mistaken (which I may be), you could email her to ask what she'd like up there. For Rafa, I think that "Professor Irizarry’s work has focused on problems related to microarray, next-generation sequencing, and genomic data. Currently, he is interested in leveraging his knowledge in translational work, e.g. developing diagnostic tools and discovering biomarkers. During his career, he as co-authored papers on a variety of topics including musical sound signals, infectious diseases, circadian patterns in health, fetal health monitoring, and estimating the effects of Hurricane María in Puerto Rico." would better highlight some accomplishments from https://www.hsph.harvard.edu/rafael-irizarry/, classic Bioconductor packages (RMA, DESeq2), EdX MOOCs, textbook (Genomic Data Science). Good that you include co-founding Bioconductor.  For Caroline Uhler, perhaps add some of her accomplishments from https://www.carolineuhler.com/ and could cut the "former Associate Professor" part?

Hope these comments are helpful!

**Comment by HelenaLC** [comment]
Thanks Levi, I full on agree. Apologies for the very general bios; first time doing anything like this... I can have an other go at it tonight. Of course, if anyone feels they have a better feel for how to write these, I’m happy to leave it to them as well.

**Comment by lwaldron** [comment]
You're doing great work @HelenaLC and I'd rather see you see it through!

**Comment by HelenaLC** [comment]
Thanks for the positivity Levi– I'm traveling Sat, so I'll wait for Aaron until I do another update early next week that includes the suggestions above. (Although, I think his bio is just so entertaining!)

**Pull request merged**
