### PR TITLE
include html file

### PR DESCRIPTION
**Pull request by LiNk-NY**
Hi Mikhail, @mdozmorov 
It looks like the page renders better with the `.html` product rather than
the `.md` file for some reason. 
Would this work for you? 

cc: @mtmorgan 
Best,
Marcel

### CODE REVIEW

**Comment by lpantano** [comment]
I can see the page nicely render.

**Comment by lpantano** [comment]
@mdozmorov, let me know if now this looks good and the other PR are not longer needed.

**Comment by mdozmorov** [comment]
It looks good. It seems impossible to make the HTML version to render within the frame and keep the menu at right, but it is better than the hand-coded Markdown tables.

@lpantano, please, merge the #82 pull request - it has Erica's changes, and I recompiled the HTML workshop page to have AMARETTO and alevin workshops. 

After this merge, the following can be closed: #78 pull request, issues #81 and #76

**Comment by LiNk-NY** [comment]
I'm not sure how to include this `<header>` part of the webpage. Any ideas?

**Comment by mdozmorov** [comment]
Not sure either. But it looks OK as an important stand-alone page. And, it is easy to click the "back" button to get to the main web site. Will keep an eye on potential solutions.

**Comment by LiNk-NY** [comment]
Hi Mikhail, @mdozmorov 
I've re-directed the output to `md` instead of HTML. This works better with the way the website is rendering. See the changes that I pushed to the main branch. 
https://github.com/Bioconductor/BioC2020/commit/3fb03e5b2ed4a8e13475371d6d695b876c15ebca

Thanks.

**Comment by mdozmorov** [comment]
Thank you, Marcel, looks great! I  wasn't familiar with "output: github_document". The solution to append header lines after knitting to .md works reliably.

Strangely, the output does not render workshops that lack the DESCRIPTION file. It was working previously, outputting the footnotes. Now, I can see the code for it is there, but the tables don't have footnotes. Like, for the 200 packages, those are not outputted:
````
    "radio1988/oneStopRNAseqWorkshop",
    "hukai916/IntegratedChIPseqWorkshop",
    "aedin/Frontiers_Supplement",
````
@LiNk-NY Marcel, can you check if this is a quick fix?
Thanks,
Mikhail

**Comment by LiNk-NY** [comment]
Hi Mikhail, @mdozmorov 
I've fixed this with the latest push to the repository. I had to add the footnotes manually since 
we are using "markdown" output instead of "html" from `knitr::kable`. 
Thanks!

**Comment by mdozmorov** [comment]
Interesting, making HTML tags in code works. The page looks complete now, I'll send a note on Slack for workshop contributors to check. Thanks, Marcel!
Mikhail

**Pull request merged**
