### PR TITLE
Fixed my workshop location and title

### PR DESCRIPTION
**Pull request by cmirzayi**

### CODE REVIEW

**Review by mdozmorov — APPROVED** [review]
Thanks, Chloe @cmirzayi. Make sure your title in the DESCRIPTION file matches your desired title, currently, it is not, https://github.com/cmirzayi/EpiForBioWorkshop/blob/master/DESCRIPTION. Next time the `workshop.Rmd` will rebuild the page, your title will be taken from your DESCRIPTION file and revert to "A workshop for concepts of epidemiology"

**Comment by cmirzayi** [comment]
Thanks Mikhail for the clarification! I want to change the location of my workshop to https://github.com/cmirzayi/EpiForBioWorkshop2020 which has a corrected DESCRIPTION and readme.md. Did I do that correctly?

**Comment by LiNk-NY** [comment]
Hi Chloe, @cmirzayi 
Thanks for making the change. I had to make the change manually and re-run the `workshops.Rmd` file to update.
Yes, it was correct to update the repository location in the code. Thanks!

**Comment by cmirzayi** [comment]
@LiNk-NY 
Thank you so much Marcel! You're the best.

**Pull request closed without merging**
